# Generated by Django 5.1.4 on 2025-05-16 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_ourproduct_last_viewed_ourproduct_view_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productview',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productview', to='product.ourproduct'),
        ),
    ]
