# Generated by Django 5.1.4 on 2025-05-16 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_productview_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productview',
            name='session',
        ),
        migrations.AddField(
            model_name='productview',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='productview',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_views', to='product.ourproduct'),
        ),
    ]
