# Generated by Django 5.1.4 on 2025-05-18 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_remove_productview_session_productview_session_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourproduct',
            name='parent_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='product.ourproduct'),
        ),
    ]
