# Generated by Django 5.1.4 on 2025-05-18 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_ourproduct_parent_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ourproduct',
            name='parent_product',
        ),
    ]
