# Generated by Django 5.1.4 on 2025-05-20 08:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_productcolor_hex_code_productimage_color'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shippinginformation',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='shippinginformation',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='shippinginformation',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='shippinginformation',
            name='delivery_location',
            field=models.CharField(choices=[('inside_dhaka', 'Inside Dhaka - 70৳'), ('outside_dhaka', 'Outside Dhaka - 130৳')], default='outside_dhaka', max_length=15),
        ),
        migrations.AlterField(
            model_name='shippinginformation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipping_infos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='shippinginformation',
            unique_together={('user', 'phone')},
        ),
    ]
