# Generated by Django 5.1.4 on 2025-05-20 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_shippinginformation_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippinginformation',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
