# Generated by Django 5.1.4 on 2025-05-20 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_shippinginformation_is_active'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shippinginformation',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='shippinginformation',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
