# Generated by Django 5.1.4 on 2025-05-20 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_alter_shippinginformation_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippinginformation',
            name='is_active',
        ),
    ]
