# Generated by Django 5.1.4 on 2025-05-20 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_shippinginformation_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_info',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='product.shippinginformation'),
        ),
    ]
