# Generated by Django 5.1.4 on 2025-05-20 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_order_is_verified_order_session_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='verification_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
