# Generated by Django 5.1.4 on 2025-07-01 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_alter_order_cart_alter_order_shipping_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourproduct',
            name='product_type',
            field=models.CharField(choices=[('clothes', 'clothes'), ('saree', 'saree'), ('other', 'other')], max_length=100),
        ),
    ]
