# Generated by Django 5.1.4 on 2025-09-03 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_alter_ourproduct_product_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ourproduct',
            name='product_type',
        ),
    ]
