# Generated by Django 5.1.4 on 2025-09-03 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_remove_ourproduct_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerreview',
            name='name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
