# Generated by Django 5.1.4 on 2025-09-06 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_scheduledmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledmessage',
            name='phone_numbers',
            field=models.TextField(blank=True, help_text='Comma-separated list', null=True),
        ),
        migrations.AddField(
            model_name='scheduledmessage',
            name='send_to_all',
            field=models.BooleanField(default=True),
        ),
    ]
