# Generated by Django 5.1.4 on 2025-11-03 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_scheduledmessage_phone_numbers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourproduct',
            name='product_make',
            field=models.CharField(blank=True, choices=[('Boutique', 'Boutique'), ('Pakistani', 'Pakistani'), ('Batik', 'Batik'), ('Silk', 'Silk'), ('Half Silk', 'Half Silk'), ('Tant', 'Tant')], max_length=100),
        ),
    ]
