# Generated by Django 5.1.4 on 2025-05-22 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pollcomment',
            old_name='text',
            new_name='content',
        ),
    ]
