# Generated by Django 5.1.4 on 2025-05-22 09:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0002_rename_text_pollcomment_content'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pollcomment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='poll',
            name='total_votes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pollcomment',
            name='dislikes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pollcomment',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('poll', 'ip_address'), ('poll', 'session_key'), ('poll', 'user')},
        ),
    ]
