# Generated by Django 5.1.4 on 2025-05-22 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0003_alter_pollcomment_options_poll_total_votes_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('poll', 'ip_address')},
        ),
    ]
