# Generated by Django 5.1.4 on 2025-05-22 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0004_alter_vote_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('poll',)},
        ),
    ]
