# Generated by Django 5.1.4 on 2025-05-22 10:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0005_alter_vote_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('poll', 'ip_address'), ('poll', 'session_key'), ('poll', 'user')},
        ),
    ]
