# Generated by Django 5.1.4 on 2025-05-23 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0007_pollcomment_disliked_by_pollcomment_liked_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollcomment',
            name='anonymous_dislikes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pollcomment',
            name='anonymous_likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pollcomment',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pollcomment',
            name='session_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
