# Generated by Django 5.1.4 on 2025-05-23 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0008_pollcomment_anonymous_dislikes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('session_key', models.CharField(max_length=100)),
                ('action', models.CharField(choices=[('like', 'Like'), ('dislike', 'Dislike')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pool.pollcomment')),
            ],
            options={
                'unique_together': {('comment', 'ip_address', 'session_key')},
            },
        ),
    ]
