# Generated by Django 5.1.4 on 2025-05-23 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0009_commentinteraction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pollcomment',
            name='anonymous_dislikes',
        ),
        migrations.RemoveField(
            model_name='pollcomment',
            name='anonymous_likes',
        ),
        migrations.RemoveField(
            model_name='pollcomment',
            name='disliked_by',
        ),
        migrations.RemoveField(
            model_name='pollcomment',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='pollcomment',
            name='liked_by',
        ),
        migrations.RemoveField(
            model_name='pollcomment',
            name='likes',
        ),
        migrations.AddField(
            model_name='pollcomment',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='CommentInteraction',
        ),
    ]
