# Generated by Django 5.1.4 on 2025-07-01 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0010_remove_pollcomment_anonymous_dislikes_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PollComment',
        ),
    ]
