# Generated by Django 5.1.4 on 2025-07-01 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0011_delete_pollcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polloption',
            name='text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
