# Generated by Django 5.1.4 on 2025-08-14 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0012_alter_polloption_text'),
        ('product', '0017_alter_ourproduct_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='polloption',
            name='product_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.featurecategory'),
        ),
    ]
