# Generated by Django 5.1.4 on 2025-08-14 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0013_polloption_product_category'),
        ('product', '0017_alter_ourproduct_product_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='polloption',
            name='product_category',
        ),
        migrations.AddField(
            model_name='poll',
            name='product_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.featurecategory'),
        ),
    ]
