# Generated by Django 5.1.4 on 2025-09-11 05:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0014_remove_polloption_product_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('poll', 'option', 'session_key'), ('poll', 'option', 'user')},
        ),
    ]
