# Generated by Django 5.1.4 on 2025-05-14 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homebanner',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.featurecategory'),
        ),
        migrations.AddField(
            model_name='homebanner',
            name='link_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
